before_script:
    - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew build

ltlcross:
  stage: test
  artifacts:
    paths:
    - debug.ltl
  script:
    - ./gradlew distTar
    - tar xfv build/distributions/Rabinizer-3.5-SNAPSHOT.tar
    - ltlcross --timeout=600 --grind=debug.ltl -F "formulas/check.ltl" '{spot} ltl2tgba -H -f %f >%O' '{rabinizer} Rabinizer-3.5-SNAPSHOT/bin/Rabinizer -o 0 -f %f >%O'