/* Generated By:JavaCC: Do not edit this line. LTLParserConstants.java */
package rabinizer.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("ALL")
public interface LTLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FOP = 5;
  /** RegularExpression Id. */
  int VOP = 6;
  /** RegularExpression Id. */
  int ROP = 7;
  /** RegularExpression Id. */
  int WOP = 8;
  /** RegularExpression Id. */
  int GOP = 9;
  /** RegularExpression Id. */
  int XOP = 10;
  /** RegularExpression Id. */
  int NEG = 11;
  /** RegularExpression Id. */
  int UOP = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int LPAR = 15;
  /** RegularExpression Id. */
  int RPAR = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int ID = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"F\"",
    "\"V\"",
    "\"R\"",
    "\"W\"",
    "\"G\"",
    "\"X\"",
    "\"!\"",
    "\"U\"",
    "\"&\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "<TRUE>",
    "<FALSE>",
    "<ID>",
  };

}
